from .user import *
from .compare import *
from .migrate import *
from .self_train import *
from .calorie_burnt import *
from .calorie_intake import *
from .activity_level import *
from .food import *
from .activity import *
from .food_category import *
from .article import *
from .uploads import *
from .quote import *