# Generated by Django 2.1.7 on 2019-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.FloatField()),
                ('x_axis_jitter', models.FloatField()),
                ('x_axis_mean_crossing_rate', models.FloatField()),
                ('x_axis_mean', models.FloatField()),
                ('x_axis_std', models.FloatField()),
                ('x_axis_var', models.FloatField()),
                ('x_axis_min', models.FloatField()),
                ('x_axis_max', models.FloatField()),
                ('x_axis_acf_mean', models.FloatField()),
                ('x_axis_acf_std', models.FloatField()),
                ('x_axis_acv_mean', models.FloatField()),
                ('x_axis_acv_std', models.FloatField()),
                ('x_axis_skew', models.FloatField()),
                ('x_axis_kurtosis', models.FloatField()),
                ('x_axis_sqrt', models.FloatField()),
                ('y_axis_jitter', models.FloatField()),
                ('y_axis_mean_crossing_rate', models.FloatField()),
                ('y_axis_mean', models.FloatField()),
                ('y_axis_std', models.FloatField()),
                ('y_axis_var', models.FloatField()),
                ('y_axis_min', models.FloatField()),
                ('y_axis_max', models.FloatField()),
                ('y_axis_acf_mean', models.FloatField()),
                ('y_axis_acf_std', models.FloatField()),
                ('y_axis_acv_mean', models.FloatField()),
                ('y_axis_acv_std', models.FloatField()),
                ('y_axis_skew', models.FloatField()),
                ('y_axis_kurtosis', models.FloatField()),
                ('y_axis_sqrt', models.FloatField()),
                ('z_axis_jitter', models.FloatField()),
                ('z_axis_mean_crossing_rate', models.FloatField()),
                ('z_axis_mean', models.FloatField()),
                ('z_axis_std', models.FloatField()),
                ('z_axis_var', models.FloatField()),
                ('z_axis_min', models.FloatField()),
                ('z_axis_max', models.FloatField()),
                ('z_axis_acf_mean', models.FloatField()),
                ('z_axis_acf_std', models.FloatField()),
                ('z_axis_acv_mean', models.FloatField()),
                ('z_axis_acv_std', models.FloatField()),
                ('z_axis_skew', models.FloatField()),
                ('z_axis_kurtosis', models.FloatField()),
                ('z_axis_sqrt', models.FloatField()),
                ('magnitude_jitter', models.FloatField()),
                ('magnitude_mean_crossing_rate', models.FloatField()),
                ('magnitude_mean', models.FloatField()),
                ('magnitude_std', models.FloatField()),
                ('magnitude_var', models.FloatField()),
                ('magnitude_min', models.FloatField()),
                ('magnitude_max', models.FloatField()),
                ('magnitude_acf_mean', models.FloatField()),
                ('magnitude_acf_std', models.FloatField()),
                ('magnitude_acv_mean', models.FloatField()),
                ('magnitude_acv_std', models.FloatField()),
                ('magnitude_skew', models.FloatField()),
                ('magnitude_kurtosis', models.FloatField()),
                ('magnitude_sqrt', models.FloatField()),
            ],
        ),
    ]
