# Generated by Django 2.1.7 on 2019-05-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgot_password',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
