# Generated by Django 2.1.7 on 2019-03-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0003_auto_20190303_1738'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datasetpersonallabel',
            table='fact_dataset_personal_label',
        ),
    ]
